// Generated by IB v0.1.4 gem. Do not edit it manually
// Run `rake design` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface TaskAddViewController : UIViewController





-(IBAction) close;
-(IBAction) cancel:(id) sender;
-(IBAction) save:(id) sender;

@end


@interface TaskListViewController : UITableViewController





-(IBAction) viewDidLoad;

@end

