// Generated by IB v0.1.4 gem. Do not edit it manually
// Run `rake design` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface TaskListViewController : UITableViewController

@property IBOutlet UILabel * task_name;

@property IBOutletCollection(UILabel) NSArray * task_names;

-(IBAction) viewDidLoad;

@end

